### PR TITLE
LocalStorageKeyStore plugin

### PR DESCRIPTION
**Pull request by challet**
Hello, 

I've wrote this plugin for an app I'm working on and thought it might be useful to share. Any recommendation would be much appreciated.
For now, it  adds the following classes : 

#### LocalStorageKeyStore

It is a plugin following the `KeyStore` interface. It is meant to use the [Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Storage) (localStorage or sessionStorage). In the tests, it uses a *[node-localstorage](https://github.com/lmaccherone/node-localstorage)* instance.

#### LocalStorageFacade

To encapsulate the access to the actual local storage. It might be extended later to work with the [WebExtension storage API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage) which have a slightly different API.

### Usage 

```javascript
const localKeyStore = new LocalStorageKeyStore();
localKeyStore.configure({ 
    storage: localStorage, // required, might also be sessionStorage or a node-localstorage instance
    prefix: "stellarkeys" // optional, defaults to "stellarkeys"
});

const keyManager = new KeyManager({
  keyStore: localKeyStore
});
```

### CODE REVIEW

**Comment by morleyzhi** [comment]
Your plugin looks great, and thanks for adding tests!

Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://docs.google.com/forms/d/1g7EF6PERciwn7zfmfke5Sir2n10yddGGSXyZsq98tVY/viewform?usp=send_form) before a change can be accepted and it doesn't look like @challet is on file as having signed it. Please follow the link to sign and let me know when you've signed. Thank you!

**Comment by challet** [comment]
Thank you @morleyzhi, I added a few changes and signed the CLA (after the checks failed).

**Comment by morleyzhi** [comment]
@cla-bot check

**Comment by morleyzhi** [comment]
@cla-bot check

**Pull request merged**
